version: '2'

services:
  db:
    image: mysql:5.7
#    ports:
#      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # enable log
      - ./mysql:/etc/mysql/mysql.conf.d/
      # init data
      - ./init:/docker-entrypoint-initdb.d
      # logs mapping
      # NOTE that this dir should have permissions
      - ./mysql-logs:/var/log/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  # opencart
  php-fpm:
    build: ./php-fpm
    expose:
      - "9000"
    volumes:
      - ../:/var/www

  apache:
    depends_on:
      - php-fpm
    build: ./apache
    ports:
      - "8080:80"
    volumes:
      - ./apache/sites:/etc/apache2/sites-available
      - ../:/var/www
      # logs mapping
      # NOTE that this dir should have permissions
      - ./opencart-logs:/var/log/apache2

  # provdb
  provdb:
    depends_on:
      - db
    image: wensun/provdb-vulnerable:latest
    ports:
      - "2222:22"
#      - "31415:80"
    restart: always
    environment:
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_ROOT_PASSWORD}
      DB_HOST: db
      DB_PORT: ${MYSQL_PORT}
      DB_DB: provdb

  provdb-frontend:
    image: wensun/provdb-frontend-vulnerable:latest
    ports:
      - "80:80"
      - "1139:139"
      - "1445:445"
    restart: always

volumes:
  mysql_data: { }
